[build]
  command = "npm run build"
  publish = "dist"
  base = "/"
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF src/server/"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
